### ISSUE TITLE
Unable to run the script 

### ISSUE THREAD

**Issue by ahammouri** [PetengDedet/WhatsApp-Analyzer#19]
Hi, I have been using this script for long time on my previous MacBook. I have recently switched to MBA M2 but I can't run the script and I keep getting these errors. 

python3 whatsapp_analyzer.py _chat.txt

Traceback (most recent call last):
  File "whatsapp_analyzer.py", line 103, in <module>
    chatline = Chatline(line=line, previous_line=previous_line, debug=args.debug)
  File "/Users/ahmadhammouri/Desktop/WhatsApp-Analyzer-master/chatline.py", line 25, in __init__
    self.parse_line(line)
  File "/Users/ahmadhammouri/Desktop/WhatsApp-Analyzer-master/chatline.py", line 169, in parse_line
    self.parse_body(body)
  File "/Users/ahmadhammouri/Desktop/WhatsApp-Analyzer-master/chatline.py", line 226, in parse_body
    emjs = self.extract_emojis(message_body)
  File "/Users/ahmadhammouri/Desktop/WhatsApp-Analyzer-master/chatline.py", line 119, in extract_emojis
    if c in emoji.UNICODE_EMOJI:
AttributeError: module 'emoji' has no attribute 'UNICODE_EMOJI'

Any help is greatly appreciated 
Thanks

**Comment by cvzi** [comment]
This happens because of version 2.0.0 of the emoji module. As a workaround you can install an older version e.g. [1.6.3](https://github.com/carpedm20/emoji/releases/tag/v1.6.3)
```sh
pip install --upgrade emoji==1.6.3
```
